import type { LanguageCode } from "@/entities/wedding/model";

export const weddingCopy = {
  RU: {
    invitation: "Приглашение на свадьбу",
    dearGuests: "Дорогие гости",
    welcome: "Будем счастливы разделить этот день с вами",
    confirm: "Подтвердить участие",
    survey: "Умный опрос гостей",
    attendingQuestion: "Вы будете с нами?",
    days: "Дней",
    hours: "Часов",
    minutes: "Минут",
    seconds: "Секунд",
    submit: "Отправить ответ",
    saving: "Сохраняем...",
    back: "Назад",
    continue: "Продолжить",
    yourName: "Ваше имя",
    namePlaceholder: "Александр",
    plusOnePlaceholder: "Имя вашего +1",
    allergiesPlaceholder: "Например, орехи или лактоза",
    trackPlaceholder: "Исполнитель — название трека",
    accepted: "Да, буду",
    declined: "Не смогу",
  },
  EN: {
    invitation: "Wedding invitation",
    dearGuests: "Dear guests",
    welcome: "We would be delighted to share this day with you",
    confirm: "RSVP",
    survey: "Guest RSVP",
    attendingQuestion: "Will you join us?",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    submit: "Send response",
    saving: "Saving...",
    back: "Back",
    continue: "Continue",
    yourName: "Your name",
    namePlaceholder: "Alexander",
    plusOnePlaceholder: "Your guest's name",
    allergiesPlaceholder: "For example, nuts or lactose",
    trackPlaceholder: "Artist — song title",
    accepted: "Yes, I will attend",
    declined: "Unfortunately, I cannot attend",
  },
  ZH: {
    invitation: "婚礼邀请",
    dearGuests: "亲爱的来宾",
    welcome: "我们诚挚邀请您与我们共度这特别的一天",
    confirm: "确认出席",
    survey: "宾客问卷",
    attendingQuestion: "您会来参加我们的婚礼吗？",
    days: "天",
    hours: "小时",
    minutes: "分钟",
    seconds: "秒",
    submit: "提交回复",
    saving: "正在保存...",
    back: "返回",
    continue: "继续",
    yourName: "您的姓名",
    namePlaceholder: "Alexander",
    plusOnePlaceholder: "同行者姓名",
    allergiesPlaceholder: "例如坚果或乳糖不耐受",
    trackPlaceholder: "歌手 — 歌曲名称",
    accepted: "是的，我会参加",
    declined: "很遗憾，我不能参加",
  },
} satisfies Record<LanguageCode, Record<string, string>>;
