import type { LanguageCode } from "@/entities/wedding/model";

export const weddingCopy = {
  RU: {
    invitation: "Приглашение на свадьбу",
    dearGuests: "Дорогие гости",
    welcome: "Будем счастливы разделить этот день с вами",
    confirm: "Подтвердить участие",
    survey: "Умный опрос гостей",
    attendingQuestion: "Вы будете с нами?",
    days: "Дней",
    hours: "Часов",
    minutes: "Минут",
    seconds: "Секунд",
    submit: "Отправить ответ",
    saving: "Сохраняем...",
    back: "Назад",
    continue: "Продолжить",
    yourName: "Ваше имя",
    namePlaceholder: "Александр",
    plusOnePlaceholder: "Имя вашего +1",
    allergiesPlaceholder: "Например, орехи или лактоза",
    trackPlaceholder: "Исполнитель — название трека",
    accepted: "Да, буду",
    declined: "Не смогу",
  },
  EN: {
    invitation: "Wedding invitation",
    dearGuests: "Dear guests",
    welcome: "We would love to share this day with you",
    confirm: "RSVP",
    survey: "Guest RSVP",
    attendingQuestion: "Will you join us?",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    submit: "Send response",
    saving: "Saving...",
    back: "Back",
    continue: "Continue",
    yourName: "Your name",
    namePlaceholder: "Alexander",
    plusOnePlaceholder: "Your guest's name",
    allergiesPlaceholder: "For example, nuts or lactose",
    trackPlaceholder: "Artist — song title",
    accepted: "Yes, I'll be there",
    declined: "I can't make it",
  },
} satisfies Record<LanguageCode, Record<string, string>>;
